[package]
name = "rover"
version = "0.1.0"
authors = ["Joao Marc <jvcmv.jvcmarcenes@gmail.com>"]
edition = "2018"

description = "marslang to LLVM compiler"
license = "MIT"

[dependencies]
text_io = "0.1.9"
structopt = "0.3.13"